import { defineConfig } from 'tsup'

// `@agentd/auth` and `@agentd/billing` are SOURCE WE OWN, not third-party dependencies, and
// they must land INSIDE both
// bundles. tsup externalises anything in `dependencies` by default, which left the ESM build
// importing a bare '@agentd/auth' specifier — fine here, fatal for every agent: a React agent app
// vendors that file and resolves nothing at that name, so `npm run build` fails for the recipient
// and never for us. The IIFE build inlines it either way; naming it here makes the two agree.
const BUNDLE_IN = ['@agentd/auth', '@agentd/billing']

// AND THE SAME AGAIN FOR THE TYPES, which took a second mechanism. `noExternal` above governs the
// JS bundle only; the .d.ts is generated by a separate pass that kept emitting
// `export { Catalog, CreditPack, Credits } from '@agentd/billing'` — a bare specifier the recipient
// cannot resolve any more than it could the JS one.
//
// The failure was quieter than the JS version and therefore worse. Nothing errored: the import
// simply did not resolve in the agent, every type behind it silently became `any`, and the first
// sign of it was `noImplicitAny` firing on a callback parameter inside the copied credits page —
// in the agent, never here, because agent-builder aliases this package to SOURCE and so never
// reads the vendored .d.ts at all.
//
// WHAT ACTUALLY FIXES IT is two things, and neither alone is enough:
//
//   1. these are `devDependencies`, not `dependencies`. tsup externalises `dependencies` by
//      default, and that governs the dts pass, which has no `noExternal`. Nothing resolves either
//      package at RUNTIME — both are bundled in — so a build-time dependency is what they are.
//   2. `paths` + `include` in tsconfig.json point at their SOURCE. The dts bundler will not follow
//      a package whose `types` is a raw .ts file, but it will happily inline a file the program
//      already contains. `@agentd/auth` was mapped that way and inlined; `@agentd/billing` was not
//      and did not, which is what made the cause visible.
//
// If a vendored .d.ts ever grows an `import ... from '@agentd/...'` line again, that is this.
const DTS = true

export default defineConfig([
  // ESM for bundlers / Node / the desktop client
  {
    entry: { index: 'src/index.ts' },
    noExternal: BUNDLE_IN,
    format: ['esm'],
    dts: DTS,
    sourcemap: true,
    clean: true
  },
  // IIFE for no-build agent apps: <script src=".../agentd-client.js"> -> window.agentd
  {
    entry: { 'agentd-client': 'src/index.ts' },
    noExternal: BUNDLE_IN,
    format: ['iife'],
    globalName: 'agentd',
    sourcemap: false,
    minify: false,
    outExtension: () => ({ js: '.js' })
  }
])
