"""`<state_dir>/tools.json` — what tools this daemon actually has, on disk, for an agent to read.

WHY A FILE. Agent Builder writes `[tools] allow` for every agent it builds, choosing from ~50
tools. Nothing let it see that list: the catalog is assembled at boot by importing every plugin
and letting each register itself, so there is no list anywhere to read. It chose from recall, and
when it could not recall a tool that already did the job, it wrote a private one instead.

WHY NOT A NEW TOOL. It already has `read`. A file needs no new capability, no new plumbing, and
no decision about who may call what.

WHY NOT A LIST IN THE SKILL. Hand-maintained, therefore drifting. This is DERIVED from the
registry that actually got built, so it cannot disagree with reality — if a plugin failed to
load, its tools are absent here too, which is correct: the file describes what this daemon has,
not what it hoped to have.

WRITTEN ON BOOT **AND ON EVERY CHANGE**. `create_tool` hot-adds without a restart and MCP servers
connect after discovery, so a boot-only snapshot would be stale in exactly the cases someone
would notice — most of all, a tool created moments ago.

ADVISORY, SO A FAILURE HERE NEVER STOPS THE DAEMON — but it is LOGGED as an error rather than
swallowed. A silently missing catalog puts the builder back to guessing, which is the problem
this exists to solve, and a quiet failure would be indistinguishable from an empty toolbox.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

log = logging.getLogger("agentd")

FILENAME = "tools.json"


def _summary(tool) -> str:
    """One line. The full descriptions are paragraphs — `create_agent`'s alone runs to 25 lines —
    and a file that costs more to read than it saves will not be read."""
    desc = (getattr(tool, "description", "") or "").strip()
    if not desc:
        return ""
    first = desc.splitlines()[0].strip()
    return first if len(first) <= 200 else first[:197] + "…"


def _source(tool) -> str:
    """Where it came from: ``plugin:<id>`` / ``mcp:<server>`` / ``internal``. Set by the
    composition root on the wrapper; derived from the tool when absent."""
    src = getattr(tool, "source", None)
    if src:
        return str(src)
    pid = getattr(tool, "_plugin_id", None)
    if pid:
        return f"plugin:{pid}"
    name = getattr(tool, "name", "") or ""
    return "mcp:" + name.split("__", 1)[0] if "__" in name else "internal"


def build(tools) -> list[dict]:
    """The catalog as plain data — name, one-line summary, source. Sorted by name so a diff
    between two boots shows what actually changed rather than import order."""
    rows = {}
    for t in tools or ():
        name = getattr(t, "name", "") or ""
        if not name or name in rows:
            continue
        rows[name] = {"name": name, "summary": _summary(t), "source": _source(t)}
    return [rows[k] for k in sorted(rows)]


def write(state_dir, tools) -> Path | None:
    """Write the catalog. Returns the path, or None if it could not be written.

    Atomic: a temp file then a rename, so a reader never catches it half-written — the same
    thing the installed-bundle ledger does next door."""
    try:
        path = Path(state_dir) / FILENAME
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "note": (
                "Generated by agentd on boot and whenever the tool catalog changes. Do not edit "
                "— it is overwritten. These are the tools available on THIS machine; an agent "
                "may be granted any of them in its agent.toml [tools] allow."
            ),
            "tools": build(tools),
        }
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        tmp.replace(path)
        return path
    except OSError as e:
        # Advisory file: never take the daemon down for it. But say so — a catalog that silently
        # is not there looks exactly like a machine with no tools.
        log.error("could not write the tool catalog to %s/%s: %s", state_dir, FILENAME, e)
        return None
