"""The accounts service's own tables, in Postgres: accounts, usage, credits, the shop, the ledger.

WHY THIS IS A FLAT SCHEMA AND NOT A TRANSLATED MIGRATION CHAIN. `_init_db` in app.py carries a
long `PRAGMA table_info` → `ALTER TABLE ADD COLUMN` sequence. Every one of those steps exists to
bring a database created by an OLDER BUILD up to today's shape; none of them describes the shape
itself. A Postgres database is created by this file at the current shape, so the steps have
nothing to upgrade — reproducing them would be translating scaffolding rather than a schema.

WHAT REPLACES THEM: the same versioned ledger identity already uses. Future changes are numbered
steps applied forward from a recorded version, which is portable as written and does not need a
`PRAGMA` equivalent. That is why identity was written this way and why the money tables were the
ones that had to be untangled.

THE ONE PLACE THE TYPES ARE NOT A STRAIGHT TRANSLATION, and it is a real defect avoided rather
than a preference:

    SQLite `INTEGER` is 64-bit. Postgres `INTEGER` is 32-bit — it stops at 2,147,483,647.

`ledger_entries.amount_micros` holds micros, so 32 bits runs out at $2,147.48 in a SINGLE
transaction. The ledger would have accepted that number for years and then refused a large
purchase with an overflow error, in the money path, in production. Every column holding money,
credits or token counts is therefore `BIGINT` here. Postgres raises on overflow rather than
wrapping, so the failure would have been loud — but "loud" at the moment a customer tries to
spend two thousand dollars is not a good enough answer.

Timestamps stay epoch doubles (`REAL` → `DOUBLE PRECISION`), matching SQLite exactly, so no query
needs date functions and stored values are unchanged.
"""

from __future__ import annotations

from typing import Any

#: Bump when adding a step to _STEPS.
SCHEMA_VERSION = 1

_STEPS: dict[int, str] = {
    1: """
    CREATE TABLE IF NOT EXISTS accounts (
        id           TEXT PRIMARY KEY,
        email        TEXT UNIQUE NOT NULL,
        pw_salt      TEXT NOT NULL,
        pw_hash      TEXT NOT NULL,
        budget_usd   DOUBLE PRECISION,            -- NULL = unlimited
        active       INTEGER NOT NULL DEFAULT 1,
        created_at   DOUBLE PRECISION NOT NULL
    );

    -- One row per model call. `event_id` is the de-duplication key: the proxy buffers a usage
    -- row when the write fails, and "failed" includes "committed, response lost" — without the
    -- key a replay silently overstates usage in a way nothing detects and nothing can undo.
    CREATE TABLE IF NOT EXISTS usage (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id     TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        ts             DOUBLE PRECISION NOT NULL,
        month          TEXT NOT NULL,             -- 'YYYY-MM' bucket for fast period sums
        model          TEXT NOT NULL DEFAULT '',
        in_tokens      BIGINT NOT NULL DEFAULT 0,
        out_tokens     BIGINT NOT NULL DEFAULT 0,
        cost_usd       DOUBLE PRECISION NOT NULL DEFAULT 0,
        run_id         TEXT NOT NULL DEFAULT '',
        turn_id        TEXT NOT NULL DEFAULT '',
        credits        BIGINT NOT NULL DEFAULT 0,
        funding_source TEXT NOT NULL DEFAULT '',
        agent_id       TEXT NOT NULL DEFAULT '',
        model_tier     TEXT NOT NULL DEFAULT '',
        cached_tokens  BIGINT NOT NULL DEFAULT 0,
        event_id       TEXT NOT NULL DEFAULT '',
        org_id         TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS ix_usage_acct_month ON usage(account_id, month);
    CREATE INDEX IF NOT EXISTS ix_usage_agent ON usage(agent_id, month);
    CREATE INDEX IF NOT EXISTS ix_usage_run ON usage(run_id);
    -- Tenant-id-leading and PARTIAL: the org rollup and the per-member cap both start from
    -- org_id, and excluding '' keeps the index empty on a deployment with no orgs.
    CREATE INDEX IF NOT EXISTS ix_usage_org
        ON usage(org_id, month, account_id) WHERE org_id <> '';
    -- PARTIAL, because rows written without an event id carry '' and a plain UNIQUE index
    -- would collide on the second of them. Keyed rows are exactly-once; the rest keep the old
    -- at-least-once behaviour.
    CREATE UNIQUE INDEX IF NOT EXISTS ix_usage_event ON usage(event_id) WHERE event_id <> '';

    -- PREPAID CREDITS: one row per GRANT, not one balance per account, because a grant carries
    -- an expiry and a class. Expiry, because an allowance that never expires is an open-ended
    -- liability against money already paid to a creator. Class, because promotional credits must
    -- never be revenue-shareable — free credits plus a creator payout is a money printer.
    CREATE TABLE IF NOT EXISTS credit_grants (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id     TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        scope          TEXT NOT NULL DEFAULT 'platform',
        credits        BIGINT NOT NULL DEFAULT 0,
        credits_used   BIGINT NOT NULL DEFAULT 0,
        credit_class   TEXT NOT NULL DEFAULT 'paid',
        model_tier_max TEXT NOT NULL DEFAULT '',
        expires_at     DOUBLE PRECISION NOT NULL DEFAULT 0,
        created_at     DOUBLE PRECISION NOT NULL,
        org_id         TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS ix_grants_acct ON credit_grants(account_id, scope);
    CREATE INDEX IF NOT EXISTS ix_grants_org ON credit_grants(org_id) WHERE org_id <> '';

    -- WHAT IS FOR SALE. Data, not code, so adding a price or a tier is a row and never a deploy.
    CREATE TABLE IF NOT EXISTS products (
        id             TEXT PRIMARY KEY,
        kind           TEXT NOT NULL DEFAULT 'credit_pack',
        title          TEXT NOT NULL DEFAULT '',
        creator_id     TEXT NOT NULL DEFAULT '',
        agent_id       TEXT NOT NULL DEFAULT '',
        price_usd      DOUBLE PRECISION NOT NULL DEFAULT 0,
        credits        BIGINT NOT NULL DEFAULT 0,
        scope          TEXT NOT NULL DEFAULT 'platform',
        model_tier_max TEXT NOT NULL DEFAULT '',
        period_days    INTEGER NOT NULL DEFAULT 30,
        active         INTEGER NOT NULL DEFAULT 1,
        created_at     DOUBLE PRECISION NOT NULL DEFAULT 0,
        seats          INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS subscriptions (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id   TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        product_id   TEXT NOT NULL,
        status       TEXT NOT NULL DEFAULT 'active',
        renews_at    DOUBLE PRECISION NOT NULL DEFAULT 0,
        created_at   DOUBLE PRECISION NOT NULL,
        org_id       TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS ix_subs_acct ON subscriptions(account_id, status);
    -- One subscription per (account, product): renewal must UPDATE the row rather than
    -- accumulate one per period, or renew-due charges N times over.
    CREATE UNIQUE INDEX IF NOT EXISTS ix_subs_acct_product
        ON subscriptions(account_id, product_id);
    CREATE INDEX IF NOT EXISTS ix_subs_due ON subscriptions(status, renews_at);

    -- WHO MAY RUN WHAT. Separate from credits on purpose: having money is not being allowed.
    CREATE TABLE IF NOT EXISTS entitlements (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        account_id   TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        agent_id     TEXT NOT NULL,
        source       TEXT NOT NULL DEFAULT 'purchase',
        min_version  TEXT NOT NULL DEFAULT '',
        expires_at   DOUBLE PRECISION NOT NULL DEFAULT 0,
        created_at   DOUBLE PRECISION NOT NULL
    );
    CREATE UNIQUE INDEX IF NOT EXISTS ix_ent_acct_agent
        ON entitlements(account_id, agent_id);

    -- The only rows in this database that grant power over other people's accounts.
    CREATE TABLE IF NOT EXISTS admins (
        account_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
        email      TEXT NOT NULL DEFAULT '',
        added_by   TEXT NOT NULL DEFAULT '',
        added_at   DOUBLE PRECISION NOT NULL DEFAULT 0,
        active     INTEGER NOT NULL DEFAULT 1
    );

    -- THE LEDGER. One row per money EVENT, so an idempotency key has somewhere unique to live
    -- and a replayed request returns the original txn_id instead of posting the money twice.
    CREATE TABLE IF NOT EXISTS ledger_txns (
        txn_id          TEXT PRIMARY KEY,
        txn_type        TEXT NOT NULL,
        ts              DOUBLE PRECISION NOT NULL,
        account_id      TEXT NOT NULL DEFAULT '',
        agent_id        TEXT NOT NULL DEFAULT '',
        ref             TEXT NOT NULL DEFAULT '',
        idempotency_key TEXT NOT NULL DEFAULT '',
        meta            TEXT NOT NULL DEFAULT ''
    );
    CREATE UNIQUE INDEX IF NOT EXISTS ix_txn_idem
        ON ledger_txns(idempotency_key) WHERE idempotency_key <> '';
    CREATE INDEX IF NOT EXISTS ix_txn_acct ON ledger_txns(account_id, ts);

    -- Append-only: never UPDATE, never DELETE. A mistake is corrected by posting its reversal,
    -- so the history of what we believed stays intact.
    --
    -- `amount_micros` is BIGINT and MUST stay BIGINT — see the module docstring. As a 32-bit
    -- INTEGER this column overflows at $2,147.48 in one transaction.
    CREATE TABLE IF NOT EXISTS ledger_entries (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        txn_id        TEXT NOT NULL,
        txn_type      TEXT NOT NULL,
        ts            DOUBLE PRECISION NOT NULL,
        account       TEXT NOT NULL,
        direction     TEXT NOT NULL,
        amount_micros BIGINT NOT NULL,
        account_id    TEXT NOT NULL DEFAULT '',
        agent_id      TEXT NOT NULL DEFAULT '',
        ref           TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS ix_entry_txn ON ledger_entries(txn_id);
    CREATE INDEX IF NOT EXISTS ix_entry_account ON ledger_entries(account, ts);
    CREATE INDEX IF NOT EXISTS ix_entry_acct ON ledger_entries(account_id, ts);
    """,
}


def create_schema(conn: Any) -> int:
    """Bring the accounts tables up to ``SCHEMA_VERSION``. Idempotent; returns the version applied.

    Takes a LIVE CONNECTION, like every other schema function here: the caller owns the
    transaction, so schema setup joins the unit of work it is already in rather than racing it.
    """
    conn.execute(
        "CREATE TABLE IF NOT EXISTS accounts_schema_version ("
        "  id INTEGER PRIMARY KEY CHECK (id = 1),"
        "  version INTEGER NOT NULL"
        ")"
    )
    row = conn.execute("SELECT version FROM accounts_schema_version WHERE id = 1").fetchone()
    current = int(row["version"]) if row else 0
    for step in range(current + 1, SCHEMA_VERSION + 1):
        script = _STEPS.get(step)
        if script:
            conn.execute(script)
    if current != SCHEMA_VERSION:
        conn.execute(
            "INSERT INTO accounts_schema_version (id, version) VALUES (1, %s) "
            "ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version",
            (SCHEMA_VERSION,),
        )
    return SCHEMA_VERSION
