"""Identity's tables and its migration ledger, in Postgres.

THE SQLITE SCHEMA WAS WRITTEN FOR THIS DAY and it shows: a versioned migration table instead of
`PRAGMA table_info`, and plain `INTEGER PRIMARY KEY` instead of `AUTOINCREMENT`. Both choices are
documented in `sqlite_schema` as being for the Postgres move, and they are why this file is a
translation rather than a redesign — the step numbers, the tables and the indexes are the same,
so the two ledgers stay comparable while both exist.

WHAT CHANGED, and nothing else did:

  * `INTEGER PRIMARY KEY` -> `GENERATED BY DEFAULT AS IDENTITY`, the mapping the SQLite file's own
    docstring names.
  * `REAL` -> `DOUBLE PRECISION`. SQLite's REAL is already a 64-bit float, so stored values are
    unchanged and no query needs rewriting.
  * Booleans stay `INTEGER NOT NULL DEFAULT 0` rather than becoming `BOOLEAN`. The stores write
    `1 if flag else 0` and read `bool(row[...])`; keeping the column type means the ported stores
    differ from their SQLite twins only in placeholders, which is the whole point.

FOREIGN KEYS TO `accounts(id)` ARE REAL HERE, as they are in SQLite — which means the accounts
tables must exist before this runs. That ordering is a property of the cutover (accounts core,
then payments, then identity), not something this file can assert on its own.
"""

from __future__ import annotations

from typing import Any

#: Bump when adding a step to _STEPS. Kept in lockstep with sqlite_schema.SCHEMA_VERSION while
#: both exist: a database migrated by one and then read by the other must agree about its shape.
SCHEMA_VERSION = 2

_STEPS: dict[int, str] = {
    1: """
    CREATE TABLE IF NOT EXISTS identities (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        provider       TEXT NOT NULL,
        subject        TEXT NOT NULL,
        account_id     TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        email          TEXT NOT NULL DEFAULT '',
        email_verified INTEGER NOT NULL DEFAULT 0,
        linked_at      DOUBLE PRECISION NOT NULL DEFAULT 0
    );
    CREATE UNIQUE INDEX IF NOT EXISTS ix_identities_provider_subject
        ON identities(provider, subject);
    CREATE INDEX IF NOT EXISTS ix_identities_account ON identities(account_id);

    CREATE TABLE IF NOT EXISTS refresh_tokens (
        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token_hash        TEXT NOT NULL,
        account_id        TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        family_id         TEXT NOT NULL,
        parent_id         BIGINT,
        client_id         TEXT NOT NULL DEFAULT '',
        device_label      TEXT NOT NULL DEFAULT '',
        issued_at         DOUBLE PRECISION NOT NULL DEFAULT 0,
        expires_at        DOUBLE PRECISION NOT NULL DEFAULT 0,
        family_expires_at DOUBLE PRECISION NOT NULL DEFAULT 0,
        used_at           DOUBLE PRECISION NOT NULL DEFAULT 0,
        revoked_at        DOUBLE PRECISION NOT NULL DEFAULT 0
    );
    CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_hash ON refresh_tokens(token_hash);
    CREATE INDEX IF NOT EXISTS ix_refresh_family ON refresh_tokens(family_id);
    CREATE INDEX IF NOT EXISTS ix_refresh_account ON refresh_tokens(account_id, revoked_at);

    CREATE TABLE IF NOT EXISTS signing_keys (
        kid          TEXT PRIMARY KEY,
        alg          TEXT NOT NULL,
        public_pem   TEXT NOT NULL,
        private_pem  TEXT NOT NULL,
        encrypted    INTEGER NOT NULL DEFAULT 0,
        created_at   DOUBLE PRECISION NOT NULL DEFAULT 0,
        expires_at   DOUBLE PRECISION NOT NULL DEFAULT 0,
        active       INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS ix_signing_keys_active ON signing_keys(active, expires_at);
    """,
    2: """
    CREATE TABLE IF NOT EXISTS orgs (
        id            TEXT PRIMARY KEY,
        name          TEXT NOT NULL,
        primary_owner TEXT NOT NULL REFERENCES accounts(id),
        seats_total   INTEGER NOT NULL DEFAULT 5,
        active        INTEGER NOT NULL DEFAULT 1,
        created_at    DOUBLE PRECISION NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS org_members (
        org_id     TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        role       TEXT NOT NULL DEFAULT 'member',
        monthly_credit_cap INTEGER NOT NULL DEFAULT 0,
        added_by   TEXT NOT NULL DEFAULT '',
        added_at   DOUBLE PRECISION NOT NULL DEFAULT 0,
        active     INTEGER NOT NULL DEFAULT 1,
        PRIMARY KEY (org_id, account_id)
    );
    CREATE INDEX IF NOT EXISTS ix_org_members_account ON org_members(account_id, active);

    CREATE TABLE IF NOT EXISTS org_domains (
        org_id   TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
        domain   TEXT NOT NULL,
        verified INTEGER NOT NULL DEFAULT 0,
        added_by TEXT NOT NULL DEFAULT '',
        added_at DOUBLE PRECISION NOT NULL DEFAULT 0,
        PRIMARY KEY (org_id, domain)
    );
    CREATE INDEX IF NOT EXISTS ix_org_domains_domain ON org_domains(domain);

    CREATE TABLE IF NOT EXISTS org_invites (
        token_hash TEXT PRIMARY KEY,
        org_id     TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
        email      TEXT NOT NULL DEFAULT '',
        role       TEXT NOT NULL DEFAULT 'member',
        expires_at DOUBLE PRECISION NOT NULL DEFAULT 0,
        created_by TEXT NOT NULL DEFAULT '',
        used_by    TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS ix_org_invites_org ON org_invites(org_id);
    """,
}


def create_schema(conn: Any) -> int:
    """Bring identity's tables up to ``SCHEMA_VERSION``. Idempotent; returns the version applied.

    Takes a LIVE CONNECTION rather than opening its own, exactly like the SQLite version — the
    caller owns the transaction, so schema setup joins whatever unit of work it is already in
    instead of racing it.
    """
    conn.execute(
        "CREATE TABLE IF NOT EXISTS identity_schema_version ("
        "  id INTEGER PRIMARY KEY CHECK (id = 1),"
        "  version INTEGER NOT NULL"
        ")"
    )
    row = conn.execute("SELECT version FROM identity_schema_version WHERE id = 1").fetchone()
    current = int(row["version"]) if row else 0
    for step in range(current + 1, SCHEMA_VERSION + 1):
        script = _STEPS.get(step)
        if script:
            # psycopg accepts a multi-statement string as long as no parameters are bound, which
            # is why the steps carry none — the same shape sqlite3's executescript took.
            conn.execute(script)
    if current != SCHEMA_VERSION:
        conn.execute(
            "INSERT INTO identity_schema_version (id, version) VALUES (1, %s) "
            "ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version",
            (SCHEMA_VERSION,),
        )
    return SCHEMA_VERSION


def backfill_local_identities(conn: Any, *, at: float) -> int:
    """Give every pre-existing account a ``local`` identity row. Returns rows created.

    Same statement as the SQLite version, without its retry loop: that loop exists because SQLite
    on EFS can be held by another writer and fail the whole boot with "database is locked".
    Postgres has row-level locking and MVCC, so the condition being retried there cannot arise
    here — keeping the loop would be cargo, and hiding a real Postgres error behind five retries
    would be worse than cargo.
    """
    cur = conn.execute(
        "INSERT INTO identities (provider, subject, account_id, email, email_verified, linked_at) "
        "SELECT 'local', a.id, a.id, a.email, 0, %s FROM accounts a "
        "WHERE NOT EXISTS ("
        "  SELECT 1 FROM identities i WHERE i.provider = 'local' AND i.subject = a.id"
        ")",
        (at,),
    )
    return int(cur.rowcount or 0)
