"""Signing keys in SQLite, with optional envelope encryption.

TWO MODES, AND THE ROW REMEMBERS WHICH ONE MADE IT. When ``AGENTD_IDENTITY_KEK`` is set the
private half is Fernet-wrapped before it is stored; otherwise it is stored as PEM. The mode is
recorded per row (``encrypted``) rather than inferred from the environment at read time, because
inferring it means setting or unsetting the KEK later turns every existing key into garbage —
a total, silent sign-out with no way back.

Not requiring a KEK is deliberate. The private key lives in the same file as the password hashes,
so on a laptop a secret drawn from the same environment protects nothing and only adds a way for
local dev to fail. Where the database is backed up somewhere the KEK is not — the deployed case —
it is exactly the protection that matters, so running without one logs a warning once.

Ed25519 is generated by default; RSA-2048 is supported for a deployment that needs RS256
compatibility. See jwt_token_issuer.py for why the size difference matters here.
"""

from __future__ import annotations

import base64
import hashlib
import logging
import os
import sqlite3
import time
import uuid

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519, rsa

from identity.application.interfaces.key_store import SigningKey
from identity.domain.errors import IdentityConfigurationError
from identity.infrastructure.jwt_token_issuer import EDDSA, RS256

log = logging.getLogger("identity.keys")

_warned_plaintext = False


def _kek() -> bytes | None:
    """The key-encryption key, derived to Fernet's expected 32 urlsafe-base64 bytes.

    Derived rather than required verbatim so an operator can set any passphrase; SHA-256 of the
    secret is the standard cheap KDF here and is adequate for a value that is already
    high-entropy infrastructure config.
    """
    raw = (os.environ.get("AGENTD_IDENTITY_KEK") or "").strip()
    if not raw:
        return None
    return base64.urlsafe_b64encode(hashlib.sha256(raw.encode("utf-8")).digest())


def _wrap(pem: str) -> tuple[str, bool]:
    key = _kek()
    if key is None:
        global _warned_plaintext
        if not _warned_plaintext:
            _warned_plaintext = True
            log.warning(
                "identity: signing keys stored UNENCRYPTED (AGENTD_IDENTITY_KEK is not set). "
                "Fine for local development; set it wherever the database is backed up."
            )
        return pem, False
    from cryptography.fernet import Fernet

    return Fernet(key).encrypt(pem.encode("utf-8")).decode("ascii"), True


def _unwrap(stored: str, encrypted: bool) -> str:
    if not encrypted:
        return stored
    key = _kek()
    if key is None:
        raise IdentityConfigurationError(
            "a signing key was stored encrypted but AGENTD_IDENTITY_KEK is not set — "
            "restore the key-encryption key, or rotate to a new signing key"
        )
    from cryptography.fernet import Fernet, InvalidToken

    try:
        return Fernet(key).decrypt(stored.encode("ascii")).decode("utf-8")
    except InvalidToken as e:
        raise IdentityConfigurationError(
            "AGENTD_IDENTITY_KEK does not decrypt the stored signing key"
        ) from e


def _generate(alg: str) -> tuple[str, str]:
    """(private_pem, public_pem) for a fresh key pair."""
    if alg == EDDSA:
        private = ed25519.Ed25519PrivateKey.generate()
    elif alg == RS256:
        private = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    else:
        raise IdentityConfigurationError(f"unsupported signing algorithm '{alg}'")
    private_pem = private.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("utf-8")
    public_pem = (
        private.public_key()
        .public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        .decode("utf-8")
    )
    return private_pem, public_pem


class SqliteKeyStore:
    """Takes a live connection, like SqlitePaymentIntentStore — the caller owns the transaction."""

    def __init__(self, conn: sqlite3.Connection, *, alg: str = EDDSA, clock=time.time):
        self._conn = conn
        self._alg = alg
        self._clock = clock

    def active(self) -> SigningKey:
        row = self._conn.execute(
            "SELECT * FROM signing_keys WHERE active = 1 ORDER BY created_at DESC LIMIT 1"
        ).fetchone()
        if row is not None:
            return self._row_to_key(row, with_private=True)
        # FIRST CALL ON A FRESH DEPLOYMENT mints the key. A service that cannot issue a token
        # until an operator runs a provisioning step is a service that is down on day one.
        return self._create(self._alg, active=True)

    def verification_keys(self) -> list[SigningKey]:
        now = float(self._clock())
        rows = self._conn.execute(
            "SELECT * FROM signing_keys WHERE active = 1 OR expires_at = 0 OR expires_at > ? "
            "ORDER BY active DESC, created_at DESC",
            (now,),
        ).fetchall()
        if not rows:
            # Serving an empty JWKS would silently break every verifier. Minting here means the
            # very first /auth/jwks.json call on a fresh deployment is correct rather than empty.
            return [self._create(self._alg, active=True)]
        return [self._row_to_key(r, with_private=False) for r in rows]

    def rotate(self, *, retire_after_s: float) -> SigningKey:
        now = float(self._clock())
        # The outgoing key keeps verifying for `retire_after_s`. That window MUST exceed the
        # access-token TTL or a token minted a second before the rotation dies before it expires.
        self._conn.execute(
            "UPDATE signing_keys SET active = 0, expires_at = ? WHERE active = 1",
            (now + max(0.0, float(retire_after_s)),),
        )
        return self._create(self._alg, active=True)

    # -- internals --------------------------------------------------------------------------

    def _create(self, alg: str, *, active: bool) -> SigningKey:
        private_pem, public_pem = _generate(alg)
        stored, encrypted = _wrap(private_pem)
        kid = uuid.uuid4().hex[:16]
        now = float(self._clock())
        self._conn.execute(
            "INSERT INTO signing_keys (kid, alg, public_pem, private_pem, encrypted, created_at, "
            "expires_at, active) VALUES (?, ?, ?, ?, ?, ?, 0, ?)",
            (kid, alg, public_pem, stored, 1 if encrypted else 0, now, 1 if active else 0),
        )
        return SigningKey(
            kid=kid, alg=alg, public_pem=public_pem, private_pem=private_pem, created_at=now
        )

    def _row_to_key(self, row, *, with_private: bool) -> SigningKey:
        private = ""
        if with_private:
            private = _unwrap(str(row["private_pem"]), bool(row["encrypted"]))
        return SigningKey(
            kid=str(row["kid"]),
            alg=str(row["alg"]),
            public_pem=str(row["public_pem"]),
            private_pem=private,
            created_at=float(row["created_at"] or 0),
            expires_at=float(row["expires_at"] or 0),
        )
