"""Identity's own tables and its own migration ledger.

TWO RULES THIS FILE FOLLOWS THAT THE MONEY TABLES DO NOT, both aimed at the Postgres move:

  * NO ``PRAGMA table_info``. ``accounts/app.py`` does add-column-if-missing by asking SQLite what
    columns a table has. It works, and it has no Postgres equivalent — so every migration written
    that way has to be rewritten by hand on the day we move. Identity instead records an integer
    version in its own table and applies steps forward from it, which is portable as written.

  * NO ``AUTOINCREMENT``. A plain ``INTEGER PRIMARY KEY`` is a rowid alias in SQLite and maps
    directly onto ``GENERATED BY DEFAULT AS IDENTITY``. The ``AUTOINCREMENT`` keyword buys only a
    guarantee against rowid reuse, which nothing here needs, and does not exist in Postgres.

Timestamps are epoch floats (``REAL`` -> ``double precision``) rather than a date type, matching
what the money tables already store, so the port stays mechanical and no query needs date
functions.

The schema shares a database FILE with accounts today (one service, one SQLite file), which is why
the foreign keys to ``accounts(id)`` are real. If identity ever moves to its own database those
become soft references on ``account_id`` and nothing else changes — the join key is the same string
either way.
"""

from __future__ import annotations

import logging
import sqlite3
import time

#: Bump when adding a step to _STEPS.
SCHEMA_VERSION = 2

_STEPS: dict[int, str] = {
    1: """
    -- WHO an account can log in as. One row per (provider, external subject).
    -- The indirection is what lets one account hold a password AND a Google login later; see
    -- application/interfaces/identity_link_store.py for why email is not the key.
    CREATE TABLE IF NOT EXISTS identities (
        id             INTEGER PRIMARY KEY,
        provider       TEXT NOT NULL,
        subject        TEXT NOT NULL,
        account_id     TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        email          TEXT NOT NULL DEFAULT '',
        email_verified INTEGER NOT NULL DEFAULT 0,
        linked_at      REAL NOT NULL DEFAULT 0
    );
    CREATE UNIQUE INDEX IF NOT EXISTS ix_identities_provider_subject
        ON identities(provider, subject);
    CREATE INDEX IF NOT EXISTS ix_identities_account ON identities(account_id);

    -- Rotating refresh tokens. `token_hash` is UNIQUE and is the only copy we keep -- the
    -- plaintext is returned to the client once and never stored.
    CREATE TABLE IF NOT EXISTS refresh_tokens (
        id                INTEGER PRIMARY KEY,
        token_hash        TEXT NOT NULL,
        account_id        TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        family_id         TEXT NOT NULL,
        parent_id         INTEGER,
        client_id         TEXT NOT NULL DEFAULT '',
        device_label      TEXT NOT NULL DEFAULT '',
        issued_at         REAL NOT NULL DEFAULT 0,
        expires_at        REAL NOT NULL DEFAULT 0,
        family_expires_at REAL NOT NULL DEFAULT 0,
        used_at           REAL NOT NULL DEFAULT 0,
        revoked_at        REAL NOT NULL DEFAULT 0
    );
    CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_hash ON refresh_tokens(token_hash);
    -- Revocation walks a family; listing devices walks an account. Both are hot enough on a
    -- sign-out-everywhere to deserve an index, and both are trivially cheap to maintain.
    CREATE INDEX IF NOT EXISTS ix_refresh_family ON refresh_tokens(family_id);
    CREATE INDEX IF NOT EXISTS ix_refresh_account ON refresh_tokens(account_id, revoked_at);

    -- Token signing keys. In the DATABASE and not an env var so they can ROTATE without a
    -- deploy: the outgoing key stays verifiable until `expires_at` while the new one signs, so
    -- nobody is signed out mid-session. See application/interfaces/key_store.py.
    CREATE TABLE IF NOT EXISTS signing_keys (
        kid          TEXT PRIMARY KEY,
        alg          TEXT NOT NULL,
        public_pem   TEXT NOT NULL,
        private_pem  TEXT NOT NULL,
        -- 1 when `private_pem` is Fernet-wrapped with AGENTD_IDENTITY_KEK. Stored per ROW, not
        -- inferred from whether the env var is set right now: a key written while the KEK was
        -- configured must stay readable, and one written without it must not be fed to a
        -- decrypt. Without this column, setting or unsetting the KEK bricks existing keys.
        encrypted    INTEGER NOT NULL DEFAULT 0,
        created_at   REAL NOT NULL DEFAULT 0,
        expires_at   REAL NOT NULL DEFAULT 0,
        active       INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS ix_signing_keys_active ON signing_keys(active, expires_at);
    """,
    2: """
    -- ORGANIZATIONS (enterprise tenancy, plan E1). An org is NOT a new kind of tenant — it is
    -- a tenant that accounts are MEMBERS of. These tables live in identity's ledger, not the
    -- money file, because membership is a fact about WHO someone is in which context, and this
    -- ledger is the one written portably for the Postgres move.
    CREATE TABLE IF NOT EXISTS orgs (
        id            TEXT PRIMARY KEY,         -- 'org_' + hex, minted like acct_
        name          TEXT NOT NULL,
        -- Exactly one; the recovery anchor. An org whose last admin left must still have one
        -- account that can act for it, the Claude-for-Work primary-owner rule.
        primary_owner TEXT NOT NULL REFERENCES accounts(id),
        seats_total   INTEGER NOT NULL DEFAULT 5,
        active        INTEGER NOT NULL DEFAULT 1,
        created_at    REAL NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS org_members (
        org_id     TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
        account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
        role       TEXT NOT NULL DEFAULT 'member',   -- owner | admin | member
        -- POLICY, not pricing (the Lovable/ChatGPT pattern): 0 = uncapped. Enforced by the
        -- funding gate when a turn draws the org pool, never at the membership door.
        monthly_credit_cap INTEGER NOT NULL DEFAULT 0,
        added_by   TEXT NOT NULL DEFAULT '',
        added_at   REAL NOT NULL DEFAULT 0,
        active     INTEGER NOT NULL DEFAULT 1,
        PRIMARY KEY (org_id, account_id)
    );
    -- "My orgs" is the switcher's query and runs at every token mint — it must never scan.
    CREATE INDEX IF NOT EXISTS ix_org_members_account ON org_members(account_id, active);

    -- Allowed email domains (offer-to-join at login). `verified` stays 0 for every row today:
    -- domain verification of any kind is deliberately deferred (user call, 2026-08-18) — the
    -- column exists so the DNS tier is a value change, not a migration.
    CREATE TABLE IF NOT EXISTS org_domains (
        org_id   TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
        domain   TEXT NOT NULL,                  -- lowercased, no '@'
        verified INTEGER NOT NULL DEFAULT 0,
        added_by TEXT NOT NULL DEFAULT '',
        added_at REAL NOT NULL DEFAULT 0,
        PRIMARY KEY (org_id, domain)
    );
    -- The login hook asks "which orgs claim this domain" — by domain, across orgs.
    CREATE INDEX IF NOT EXISTS ix_org_domains_domain ON org_domains(domain);

    CREATE TABLE IF NOT EXISTS org_invites (
        token_hash TEXT PRIMARY KEY,             -- sha256; plaintext returned once, never stored
        org_id     TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
        email      TEXT NOT NULL DEFAULT '',     -- '' = open link
        role       TEXT NOT NULL DEFAULT 'member',
        expires_at REAL NOT NULL DEFAULT 0,
        created_by TEXT NOT NULL DEFAULT '',
        used_by    TEXT NOT NULL DEFAULT ''
    );
    CREATE INDEX IF NOT EXISTS ix_org_invites_org ON org_invites(org_id);
    """,
}


def create_schema(conn: sqlite3.Connection) -> int:
    """Bring identity's tables up to ``SCHEMA_VERSION``. Idempotent; returns the version applied.

    Takes a LIVE CONNECTION rather than opening its own, exactly like
    ``SqlitePaymentIntentStore.create_schema`` — the caller owns the transaction, so schema setup
    joins whatever unit of work it is already in instead of racing it.
    """
    conn.execute(
        "CREATE TABLE IF NOT EXISTS identity_schema_version ("
        "  id INTEGER PRIMARY KEY CHECK (id = 1),"
        "  version INTEGER NOT NULL"
        ")"
    )
    row = conn.execute("SELECT version FROM identity_schema_version WHERE id = 1").fetchone()
    current = int(row[0]) if row else 0
    for step in range(current + 1, SCHEMA_VERSION + 1):
        script = _STEPS.get(step)
        if script:
            conn.executescript(script)
    if current != SCHEMA_VERSION:
        conn.execute(
            "INSERT INTO identity_schema_version (id, version) VALUES (1, ?) "
            "ON CONFLICT(id) DO UPDATE SET version = excluded.version",
            (SCHEMA_VERSION,),
        )
    return SCHEMA_VERSION


def backfill_local_identities(conn: sqlite3.Connection, *, at: float, retries: int = 5) -> int:
    """Give every pre-existing account a ``local`` identity row. Returns rows created.

    THE MIGRATION THAT MAKES THIS NON-DESTRUCTIVE. Accounts that signed up before identity existed
    have a password on the accounts row and no identity record, so the resolution path in
    ``PrincipalService`` would not find them and would mint a SECOND account on their next login —
    a new account id, an empty credit balance, and no way to notice. One row each, keyed on the
    account id as the subject, and every existing user lands on their own account.

    Idempotent: the unique index makes a second run a no-op.

    RETRIES, THEN GIVES UP WITHOUT RAISING — and both halves of that matter. On EFS the database
    can be briefly held by another writer (a deploy that overlaps two tasks), and a bare attempt
    dies with "database is locked" *inside application startup*, which kills the container: the
    service will not boot because a backfill could not get a lock for a second. That is a far
    worse outcome than the backfill being late.

    Late is safe here precisely because this is idempotent and runs on EVERY boot, so a skipped
    pass is picked up by the next one. It is deliberately NOT silent: a WARNING says the adoption
    has not happened yet, which is the thing an operator would want to know if it never does.
    """
    delay = 0.2
    for attempt in range(max(1, retries)):
        try:
            cur = conn.execute(
                "INSERT INTO identities (provider, subject, account_id, email, email_verified, linked_at) "
                "SELECT 'local', a.id, a.id, a.email, 0, ? FROM accounts a "
                "WHERE NOT EXISTS ("
                "  SELECT 1 FROM identities i WHERE i.provider = 'local' AND i.subject = a.id"
                ")",
                (at,),
            )
            return int(cur.rowcount or 0)
        except sqlite3.OperationalError as e:
            if "locked" not in str(e).lower() and "busy" not in str(e).lower():
                raise
            if attempt == retries - 1:
                logging.getLogger("identity").warning(
                    "identity backfill skipped this boot (%s); it is idempotent and will run on "
                    "the next start. Existing accounts cannot sign in until it does.", e
                )
                return 0
            time.sleep(delay)
            delay *= 2
    return 0
