"""Designs a post's slides: the agent's model writes each slide as HTML/CSS — layout, type, colour
blocks, shapes, the photos placed, a clip's slot, CSS motion — following the design playbook, from
scratch or adapted from a template — and, when the library has them, following a DESIGN REFERENCE
(a picture of a design worth following: its structure, rebuilt with this post's own pictures and
words — never its words, logos or photos); it is rendered, and an art-director pass looks at the
render (beside the reference) and sends back what a professional would fix. Up to three rounds
per slide.

The words are the plan's (the slide's cues), exactly. The pictures are the collection's — the
slide's own item first, then others of the same product it may use (a collage). Nothing is
generated by an image model: designing costs model calls only.

The slides are designed AT ONCE (each its own rounds), and where each one is — designing,
reviewing, its latest preview, what is still to fix — is written as it moves, for the window to
show. A run that is stopped stops before its next model call.
"""

from __future__ import annotations

import contextvars
import json
import threading
from concurrent.futures import ThreadPoolExecutor
from typing import Callable

from ad_generation.application.interfaces.brand_store import BrandStore
from ad_generation.application.interfaces.collection_store import CollectionStore
from ad_generation.application.design_reference_picker import DesignReferencePicker
from ad_generation.application.interfaces.design_reference_store import DesignReferenceStore
from ad_generation.application.interfaces.design_renderer import DesignRenderer
from ad_generation.application.interfaces.design_template_store import DesignTemplateStore
from ad_generation.application.interfaces.post_store import PostStore
from ad_generation.application.interfaces.progress_reporter import ProgressReporter
from ad_generation.application.interfaces.reasoner import Reasoner
from ad_generation.application.interfaces.slide_renderer import SlideRenderer
from ad_generation.domain.design_progress import DesignProgress, SlideDesignState
from ad_generation.domain.design_reference import DesignReference
from ad_generation.domain.design_rules import DesignRules
from ad_generation.domain.instagram_format import size
from ad_generation.domain.post import Post, Slide

_ROUNDS = 3
_EXTRA_PICTURES = 3  # other pictures of the same product the designer may use
_AT_ONCE = 8  # slides designed in parallel
# What of the brand a design may use: its look. Its name, handle and tagline are words — a slide
# carries only the plan's words, and the sign-off is a slide's words when the plan puts it there.
_BRAND_LOOK = ("heading_font", "label_font", "text_color", "accent_color")


class DesignStopped(RuntimeError):
    """The run was stopped (the user pressed Stop, or the job was cancelled)."""


class DesignService:
    def __init__(
        self,
        reasoner: Reasoner,
        posts: PostStore,
        collections: CollectionStore,
        brands: BrandStore,
        templates: DesignTemplateStore,
        references: DesignReferenceStore,
        picker: DesignReferencePicker,
        renderer: DesignRenderer,
        frames: SlideRenderer,
        instructions: str,
        playbook: str,
        critique: str,
        progress: ProgressReporter,
        clock: Callable[[], float],
    ) -> None:
        self._reasoner = reasoner
        self._posts = posts
        self._collections = collections
        self._brands = brands
        self._templates = templates
        self._references = references
        self._picker = picker
        self._renderer = renderer
        self._frames = frames
        self._prompt = instructions.strip() + "\n\n" + playbook.strip()
        self._critique = critique
        self._progress = progress
        self._clock = clock
        self._lock = threading.Lock()

    def design(
        self, slug: str, numbers: list[int], notes: str, template: str, references: list[str] | None = None,
        should_stop: Callable[[], bool] = lambda: False,
    ) -> list[dict]:
        """Design the slides numbered (1-based; [] = all) -> per slide: its preview, the design's
        path, the reference it followed, and what the art director still wanted fixed (empty when
        it passed). `references`: the slugs to follow (one -> every slide follows it); [] -> no
        reference; None -> a slide designed before keeps the reference it followed, and the others
        are chosen from the references this post already follows (its family) — or, for a post
        not yet designed, from the whole library. `notes` is the user's brief, in their words: the
        choice of references, the designer and the art director all follow it. A slide that fails
        does not stop the others; the failures are raised together once the rest are kept."""
        post = self._posts.get(slug)
        chosen = numbers or list(range(1, len(post.slides) + 1))
        bad = [n for n in chosen if not 1 <= n <= len(post.slides)]
        if bad:
            raise ValueError(f"post {slug} has slides 1-{len(post.slides)}, not {bad}")
        start = self._templates.get(template) if template else None
        start_html = self._templates.html(start) if start else ""
        follows: dict[int, DesignReference] = {}
        if references is None:
            library = {r.slug: r for r in self._references.all()}
            family = {s.reference: library[s.reference] for s in post.slides if s.reference in library}
            follows = {n: library[post.slides[n - 1].reference] for n in chosen if post.slides[n - 1].reference in library}
            offered = list(family.values()) or list(library.values())
        else:
            offered = [self._references.get(s) for s in references]
        rest = [n for n in chosen if n not in follows]
        if rest and len(offered) > 1:
            self._progress.say(f"choosing references from {len(offered)}")
        follows.update(self._picker.pick(post, rest, offered, notes) if rest else {})

        now = self._clock()
        progress = DesignProgress(post=slug, active=True, started=now, updated=now,
                                  slides={n: SlideDesignState(rounds=_ROUNDS, reference=follows[n].slug if n in follows else "") for n in chosen})
        self._posts.save_design_progress(progress)
        self._progress.say(f"designing {len(chosen)} slide(s) at once")
        results: dict[int, dict] = {}
        failures: dict[int, str] = {}
        try:
            with ThreadPoolExecutor(max_workers=min(_AT_ONCE, len(chosen))) as pool:
                # Each slide's thread carries this run's context (its workspace, the account its
                # model calls are billed to) — a plain pool thread would start without it.
                futures = {
                    n: pool.submit(contextvars.copy_context().run, self._one, post, n, notes, start_html, follows.get(n), progress, should_stop)
                    for n in chosen
                }
                for n, future in futures.items():
                    try:
                        slide, result = future.result()
                    except DesignStopped:
                        self._mark(progress, n, state="stopped")
                        continue
                    except Exception as e:  # noqa: BLE001 — kept per slide, raised together below
                        failures[n] = f"{type(e).__name__}: {e}"
                        self._mark(progress, n, state="failed", problems=[failures[n]])
                        continue
                    with self._lock:
                        fresh = self._posts.get(slug)
                        fresh.slides[n - 1] = slide
                        self._posts.save(fresh)
                    results[n] = result
        finally:
            with self._lock:
                progress.active = False
                progress.updated = self._clock()
                self._posts.save_design_progress(progress)
        if should_stop():
            raise DesignStopped(f"stopped — {len(results)} of {len(chosen)} slide(s) designed and kept")
        if failures:
            raise ValueError(f"{len(results)} slide(s) designed and kept; failed: " + "; ".join(f"slide {n}: {why}" for n, why in failures.items()))
        return [results[n] for n in chosen]

    def _mark(self, progress: DesignProgress, n: int, **changes) -> None:
        """Move one slide's state and write the whole run's progress (slides run in parallel)."""
        with self._lock:
            state = progress.slides[n]
            for k, v in changes.items():
                setattr(state, k, v)
            progress.updated = self._clock()
            self._posts.save_design_progress(progress)

    def _one(
        self, post: Post, n: int, notes: str, template_html: str, reference: DesignReference | None,
        progress: DesignProgress, should_stop: Callable[[], bool],
    ) -> tuple[Slide, dict]:
        slide = post.slides[n - 1]
        media = self._media(post, slide)
        allowed = {m["path"] for m in media}
        clip = slide.item if slide.kind == "video" else ""
        w, h = size(post.format)
        words = [" ".join(c.text.split()) for c in slide.cues]
        brand = self._brands.get().to_dict()
        facts = {
            "canvas": {"width": w, "height": h}, "format": post.format, "purpose": slide.note,
            "words": words, "media": media, "main_item": slide.item, "brand": {k: brand[k] for k in _BRAND_LOOK},
            "brief": notes or None, "design_notes": brand["design_notes"] or None, "template": template_html or None,
            "reference": {"name": reference.name, "spec": reference.spec} if reference else None,
        }
        looks = [m["path"] if m["kind"] == "image" else self._frames.still_of(m["path"], f"{self._posts.scratch('design')}/{post.slug}-{n}-{i}.jpg")
                 for i, m in enumerate(media)]
        # The reference is looked at, never used: it rides LAST, after the slide's own media, and
        # its path is not among the files a design may load.
        if reference:
            looks.append(reference.image)
        judge = {
            "words": words, "format": post.format, "purpose": slide.note, "brief": notes or None,
            "design_notes": brand["design_notes"] or None,
            "reference": {"name": reference.name, "spec": reference.spec} if reference else None,
        }
        previous, problems, html_path, preview = "", [], "", ""
        for round_ in range(1, _ROUNDS + 1):
            if should_stop():
                raise DesignStopped(f"slide {n} stopped")
            self._mark(progress, n, state="designing", round=round_)
            ask = {**facts, "previous": previous or None, "problems": problems or None}
            answer = self._reasoner.read_images(self._prompt + "\n\nFACTS:\n" + json.dumps(ask, ensure_ascii=False), looks)
            html = str(answer.get("html") or "")
            problems = DesignRules.problems(html, allowed, clip)
            if problems:
                previous = html
                self._mark(progress, n, problems=problems)
                continue
            html_path = self._posts.write_design(post.slug, n, html)
            preview = self._renderer.still(html_path, post.format, self._posts.design_preview(post.slug, n))
            if should_stop():
                raise DesignStopped(f"slide {n} stopped")
            self._mark(progress, n, state="reviewing", preview=preview)
            verdict = self._reasoner.read_images(
                self._critique + "\n\nFACTS:\n" + json.dumps(judge, ensure_ascii=False), [preview, *([reference.image] if reference else [])]
            )
            problems = [str(p) for p in verdict.get("problems") or [] if str(p).strip()]
            self._mark(progress, n, problems=problems)
            if verdict.get("ok") and not problems:
                break
            previous = html
            self._progress.say(f"slide {n}: round {round_} — {len(problems)} thing(s) to fix")
        if not html_path:
            raise ValueError(f"no design followed the rules after {_ROUNDS} tries — " + "; ".join(problems))
        self._mark(progress, n, state="done", preview=preview, problems=problems)
        return Slide.from_dict({**slide.to_dict(), "design": html_path, "preview": preview, "reference": reference.slug if reference else ""}), {
            "slide": n, "design": html_path, "preview": preview, "reference": reference.slug if reference else "", "still_to_fix": problems,
        }

    def _media(self, post: Post, slide: Slide) -> list[dict]:
        items = self._collections.get(post.collection).items
        main = next((i for i in items if i.path == slide.item), None)
        if main is None:
            raise ValueError(f"slide item {slide.item} is no longer in collection {post.collection}")
        others = [i for i in items if i.product == main.product and i.path != main.path and i.kind == "image"][:_EXTRA_PICTURES]
        return [{"path": i.path, "kind": i.kind, "product": i.product, "main": i.path == main.path} for i in [main, *others]]
