/**
 * Build @agentd/canvas → ONE self-contained pair an agent app vendors:
 *
 *   dist/agentd-canvas.js    IIFE, global `agentdCanvas` (React + fabric + the shell's
 *                            canvas components, straight from ../ui/src — no copies)
 *   dist/agentd-canvas.css   the canvas rules EXTRACTED from the shell's styles.css at build
 *                            time (every `.cv-` / `.ws-` block + the theme variables they
 *                            use, with the shell's values as :root fallbacks). Extraction,
 *                            not duplication: restyle the shell and rebuild — apps follow.
 *
 * Then vendors both into every agent that declares a `ui/vendor/` — currently figure-create.
 */

import { build } from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const pkg = path.resolve(here, '..')
const v2 = path.resolve(pkg, '..', '..')
const uiSrc = path.join(v2, 'clients', 'ui', 'src')
const dist = path.join(pkg, 'dist')
fs.mkdirSync(dist, { recursive: true })

// ---- JS: bundle the entry (which imports the shell's own component sources) --------------
await build({
  entryPoints: [path.join(pkg, 'src', 'index.tsx')],
  bundle: true,
  format: 'iife',
  globalName: 'agentdCanvas',
  outfile: path.join(dist, 'agentd-canvas.js'),
  minify: true,
  jsx: 'automatic',
  // ONE REACT, whatever the disk says. This entry pulls in files from TWO packages — this one and
  // clients/ui — and esbuild resolves `react` relative to the file that imports it, so ui's
  // components bound to clients/node_modules/react while this package's bound to its own. Two
  // instances of React in one bundle is not a size problem, it is a broken one: hooks read a
  // dispatcher off the module singleton, so the second copy's hooks see null and every component
  // using one dies with "Invalid hook call". It surfaced the day the clients workspace gained its
  // own react (the tree that had them hoisted looked fine), which is exactly the kind of thing a
  // build must pin rather than notice.
  alias: {
    react: path.join(pkg, 'node_modules', 'react'),
    'react-dom': path.join(pkg, 'node_modules', 'react-dom'),
  },
  define: { 'process.env.NODE_ENV': '"production"' },
  loader: { '.svg': 'dataurl' },
  logLevel: 'info',
})

// ---- CSS: extract the canvas rules + the variables they use from the shell ---------------
const css = fs.readFileSync(path.join(uiSrc, 'styles.css'), 'utf-8')
const blocks = css.match(/[^{}]*\{[^{}]*\}/g) || []
const canvasBlocks = blocks.filter((b) => {
  const sel = b.split('{')[0]
  return sel.includes('.cv-') || sel.includes('.ws-') || sel.includes('.markdown')
})
const used = new Set()
for (const b of canvasBlocks) for (const m of b.matchAll(/var\((--[a-z0-9-]+)/g)) used.add(m[1])
// each var's value from the shell's base :root block (light theme = the app default)
const rootBlock = blocks.find((b) => b.split('{')[0].trim() === ':root') || ''
const varLines = []
for (const name of used) {
  const m = rootBlock.match(new RegExp(`${name}\\s*:\\s*([^;]+);`))
  if (m) varLines.push(`  ${name}: ${m[1].trim()};`)
}
// ---- the WHOLE stylesheet, for `mountShell` ---------------------------------------------
// The narrow sheet above exists for an app that borrows the canvas alone and keeps its own look.
// An app that mounts the full surface is not borrowing a widget, it IS the agentd window — and
// picking selectors for that is a losing game: every shell restyle would silently half-apply.
// Copied rather than curated, so the two can never disagree, and written next to the other
// artifact so vendoring stays one step.
fs.writeFileSync(
  path.join(dist, 'agentd-shell.css'),
  [
    '/* GENERATED by @agentd/canvas build — a verbatim copy of clients/ui/src/styles.css.',
    '   Do not edit: rebuild the package instead (npm run build in v2/clients/canvas). */',
    css,
  ].join('\n')
)

const out = [
  '/* GENERATED by @agentd/canvas build — extracted from clients/ui/src/styles.css. Do not edit. */',
  `:root {\n${varLines.join('\n')}\n}`,
  ...canvasBlocks.map((b) => b.trim()),
].join('\n\n')
fs.writeFileSync(path.join(dist, 'agentd-canvas.css'), out)
console.log(`css: ${canvasBlocks.length} blocks, ${used.size} vars -> agentd-canvas.css`)

// ---- vendor into the agents that use it ---------------------------------------------------
// Each target names WHAT it borrows: the canvas widget alone, or the whole window. Listing the
// files per agent rather than copying all three everywhere keeps a 60KB stylesheet out of an app
// that only wanted a viewer — and makes the difference visible here instead of in a page's <head>.
const TARGETS = [
  { dir: path.join(v2, 'agents', 'figure-create', 'ui', 'vendor'), files: ['agentd-canvas.js', 'agentd-canvas.css'] },
  { dir: path.join(v2, 'agents', 'figure-creator', 'ui', 'vendor'), files: ['agentd-canvas.js', 'agentd-shell.css'] },
]
for (const { dir, files } of TARGETS) {
  fs.mkdirSync(dir, { recursive: true })
  for (const f of files) {
    fs.copyFileSync(path.join(dist, f), path.join(dir, f))
  }
  console.log(`vendored -> ${path.relative(v2, dir)} (${files.join(', ')})`)
}
