/**
 * Build @agentd/canvas → ONE self-contained pair an agent app vendors:
 *
 *   dist/agentd-canvas.js    IIFE, global `agentdCanvas` (React + fabric + the shell's
 *                            canvas components, straight from ../ui/src — no copies)
 *   dist/agentd-canvas.css   the canvas rules EXTRACTED from the shell's styles.css at build
 *                            time (every `.cv-` / `.ws-` block + the theme variables they
 *                            use, with the shell's values as :root fallbacks). Extraction,
 *                            not duplication: restyle the shell and rebuild — apps follow.
 *
 * Then vendors both into every agent that declares a `ui/vendor/` — currently figure-create.
 */

import { build } from 'esbuild'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const pkg = path.resolve(here, '..')
const v2 = path.resolve(pkg, '..', '..')
const uiSrc = path.join(v2, 'clients', 'ui', 'src')
const dist = path.join(pkg, 'dist')
fs.mkdirSync(dist, { recursive: true })

// ---- JS: bundle the entry (which imports the shell's own component sources) --------------
await build({
  entryPoints: [path.join(pkg, 'src', 'index.tsx')],
  bundle: true,
  format: 'iife',
  globalName: 'agentdCanvas',
  outfile: path.join(dist, 'agentd-canvas.js'),
  minify: true,
  jsx: 'automatic',
  define: { 'process.env.NODE_ENV': '"production"' },
  loader: { '.svg': 'dataurl' },
  logLevel: 'info',
})

// ---- CSS: extract the canvas rules + the variables they use from the shell ---------------
const css = fs.readFileSync(path.join(uiSrc, 'styles.css'), 'utf-8')
const blocks = css.match(/[^{}]*\{[^{}]*\}/g) || []
const canvasBlocks = blocks.filter((b) => {
  const sel = b.split('{')[0]
  return sel.includes('.cv-') || sel.includes('.ws-') || sel.includes('.markdown')
})
const used = new Set()
for (const b of canvasBlocks) for (const m of b.matchAll(/var\((--[a-z0-9-]+)/g)) used.add(m[1])
// each var's value from the shell's base :root block (light theme = the app default)
const rootBlock = blocks.find((b) => b.split('{')[0].trim() === ':root') || ''
const varLines = []
for (const name of used) {
  const m = rootBlock.match(new RegExp(`${name}\\s*:\\s*([^;]+);`))
  if (m) varLines.push(`  ${name}: ${m[1].trim()};`)
}
const out = [
  '/* GENERATED by @agentd/canvas build — extracted from clients/ui/src/styles.css. Do not edit. */',
  `:root {\n${varLines.join('\n')}\n}`,
  ...canvasBlocks.map((b) => b.trim()),
].join('\n\n')
fs.writeFileSync(path.join(dist, 'agentd-canvas.css'), out)
console.log(`css: ${canvasBlocks.length} blocks, ${used.size} vars -> agentd-canvas.css`)

// ---- vendor into the agents that use it ---------------------------------------------------
const TARGETS = [path.join(v2, 'agents', 'figure-create', 'ui', 'vendor')]
for (const dir of TARGETS) {
  fs.mkdirSync(dir, { recursive: true })
  for (const f of ['agentd-canvas.js', 'agentd-canvas.css']) {
    fs.copyFileSync(path.join(dist, f), path.join(dir, f))
  }
  console.log(`vendored -> ${path.relative(v2, dir)}`)
}
